# -*- coding: utf-8 -*-
"""Feedlot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sb9rno9XPVjBYKvl8NkekOtsOB7Zoj21
"""

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.preprocessing import LabelEncoder

# Load dataset
data_path = "cattle_feedlot_data.csv"
cattle_df = pd.read_csv(data_path)

# Encoding categorical variables
label_encoder = LabelEncoder()
cattle_df['Feed_Type_Encoded'] = label_encoder.fit_transform(cattle_df['Feed_Type'])

# Features and target
X = cattle_df[['Weight', 'Age_in_Months', 'Daily_Feed_Amount', 'Avg_Gain_Per_Day', 'Days_on_Feed', 'Feed_Type_Encoded']]
y = cattle_df['Market_Ready']

# Splitting the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Building a Random Forest Classifier
rf_classifier = RandomForestClassifier(n_estimators=100, random_state=42)
rf_classifier.fit(X_train, y_train)

# Making predictions
y_pred = rf_classifier.predict(X_test)

# Evaluating the model
accuracy = accuracy_score(y_test, y_pred)
classification_rep = classification_report(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)

# Output results
print(f"Accuracy: {accuracy}")
print(f"Classification Report:\\n{classification_rep}")
print(f"Confusion Matrix:\\n{conf_matrix}")